### ISSUE TITLE
Insert is O(n^2)?

### ISSUE THREAD

**Issue by lacker** [umpc/go-sortedmap#40]
According to the readme, insert is average time O(n^2) in this library. That seems strange for a sorted map, is that accurate or is it a readme error or am I misunderstanding something?

**Comment by umpc** [comment]
You're right, it is strange: So strange in fact that I believe it deserves a proper explanation. (Prepare for a chuckle)

I had completely misunderstood how to measure Big-O complexity and was measuring them relative to 0, and effectively compared each type of method to each other type of method within this library, by fitting the benchmark times against linear equations that were similar functions to what are commonly used in Big-O notation: ```y=log(x), y=x^2, etc.``` I am quite fortunate that this is the only time that I have ever tried to do such a thing.

I have taken a look at what the underlying operations are actually doing and have updated the Readme accordingly.

Thank you so much.
